apiVersion: v1
kind: Namespace
metadata:
  name: podlogger-system
spec:
  finalizers:
    - kubernetes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podlogger-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podlogger-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podlogger-role
subjects:
  - kind: ServiceAccount
    name: podlogger-sa
    namespace: podlogger-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podlogger-sa
  namespace: podlogger-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: podlogger-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: podlogger-sa
      containers:
        - image: ko://github.com/aerfio/podlogger
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10

